va_bulkfeaturemanager:
  path: va_bulkfeaturemanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::displayProductConfiguration'

va_bulkfeaturemanager_features_list:
  path: va_bulkfeaturemanager/features
  methods: GET
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::indexAction'

va_bulkfeaturemanager_search_feature:
  path: va_bulkfeaturemanager/features
  methods: POST
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::searchAction'

va_bulkfeaturemanager_add_feature:
  path: va_bulkfeaturemanager/features/add
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::addNewFeatureAction'
