# Main module page
#va_bulkfeaturemanager:
#  path: va_bulkfeaturemanager/configuration
#  methods: [GET, POST]
#  defaults:
#    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::displayProductConfiguration'

# Feature grid list page
va_bulkfeaturemanager_features_list:
  path: va_bulkfeaturemanager/features
  methods: GET
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::featureListGridAction'

#Features list - search controller action
va_bulkfeaturemanager_search_feature:
  path: va_bulkfeaturemanager/features
  methods: POST
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::searchAction'

#Feature add form
va_bulkfeaturemanager_add_feature:
  path: va_bulkfeaturemanager/features/add
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::addNewFeatureAction'

#Feature edit form
va_bulkfeaturemanager_edit_feature:
  path: va_bulkfeaturemanager/features/{featureId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::editFeatureAction'
  requirements:
    featureId: \d+
#Feature delete form
va_bulkfeaturemanager_delete_feature:
  path: va_bulkfeaturemanager/features/{featureId}/delete
  methods: DELETE
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::deleteFeatureAction'
  requirements:
    featureId: \d+

# Feature values list
va_bulkfeaturemanager_feature_values:
  path: va_bulkfeaturemanager/feature/{featureId}/values
  methods: GET
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::displayFeatureValuesAction'
  requirements:
    featureId: \d+

# Feature values search controller
va_bulkfeaturemanager_feature_value_search:
  path: va_bulkfeaturemanager/feature/{featureId}/values
  methods: POST
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::searchFeatureValueAction'
  requirements:
      featureId: \d+

# Feature values add form
va_bulkfeaturemanager_add_feature_value:
  path: va_bulkfeaturemanager/feature/value/add
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::addNewFeatureValueAction'

# Feature values edit form
va_bulkfeaturemanager_feature_value_edit:
  path: va_bulkfeaturemanager/feature/value/{featureValueId}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::editFeatureValueAction'
    requirements:
      featureValueId: \d+

# Feature values delete form
va_bulkfeaturemanager_feature_value_delete:
  path: va_bulkfeaturemanager/feature/value/{featureValueId}
  methods: DELETE
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::deleteFeatureValue'
    requirements:
      featureValueId: \d+

# Feature values delete bulk action
va_bulkfeaturemanager_feature_value_delete_bulk:
  path: va_bulkfeaturemanager/feature/value
  methods: POST
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::deleteBulkFeatureValue'

va_bulkfeaturemanager_export_products:
  path: va_bulkfeaturemanager/configuration/exportProducts
  methods: [GET]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::exportFileFeatureProducts'

va_bulkfeaturemanager_export_features:
  path: va_bulkfeaturemanager/configuration/exportFeatures
  methods: [GET]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::exportFileFeature'

va_bulkfeaturemanager_export_featureValues:
  path: va_bulkfeaturemanager/configuration/exportValues
  methods: [GET]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::exportFileFeatureValue'

va_bulkfeaturemanager_import:
  path: va_bulkfeaturemanager/configuration/import
  methods: [GET]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::importIndexAction'

va_bulkfeaturemanager_import_process:
  path: va_bulkfeaturemanager/configuration/import/process
  methods: [POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::importFileProcess'

va_bulkfeaturemanager_import_upload:
  path: va_bulkfeaturemanager/configuration/import/upload
  methods: [POST]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\BulkFeatureManagerController::uploadFile'


# API

va_bulkfeaturemanager:
  path: va_bulkfeaturemanager/configuration
  methods: [ GET ]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\UnitPriceRestApiController::getRouteLinks'

va_bulkfeaturemanager_get_features_data:
  path: va_bulkfeaturemanager/features_api
  methods: [ GET ]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\UnitPriceRestApiController::getFeaturesData'


va_bulkfeaturemanager_get_products_data:
  path: va_bulkfeaturemanager/products/{productsLimit}
  methods: [ GET, POST ]
  defaults:
    _controller: 'Va_bulkfeaturemanager\Controller\UnitPriceRestApiController::getProductsList'
    requirements:
      productsLimit: \d+

