services:
  _defaults:
    public: true
# form type
  Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType:
    class: Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

# form data provider
  prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_provider:
    class: 'Va_bulkfeaturemanager\Form\BulkFeatureManagerDataProvider'


  # data handler
  prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_provider'
      - 'Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType'
      - 'BulkFeatureManager'

# grid factory
  prestashop.module.va_bulkfeaturemanager.grid.bulkfeaturemanager.grid_definition_factory:
    class: 'Va_bulkfeaturemanager\Grid\Factory\BulkFeatureManagerGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
