services:
  _defaults:
    public: true
# form type
  Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType:
    class: Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

# form data provider - featuremanager
  prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_provider:
    class: 'Va_bulkfeaturemanager\Form\BulkFeatureManagerDataProvider'


  # data handler
  prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.va_bulkfeaturemanager.form.bulkfeaturemanager_data_provider'
      - 'Va_bulkfeaturemanager\Form\BulkFeatureManagerFormType'
      - 'BulkFeatureManager'

# grid factory
  #1
  prestashop.module.va_bulkfeaturemanager.grid.bulkfeaturemanager.grid_definition_factory:
    class: 'Va_bulkfeaturemanager\Grid\GridProductsFeature\Factory\BulkFeatureManagerGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
  #2
  prestashop.module.va_bulkfeaturemanager.grid.query_builder.bulkfeaturemanager:
    class: 'Va_bulkfeaturemanager\Grid\GridProductsFeature\Query\BulkFeatureQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
  #3
  prestashop.module.va_bulkfeaturemanager.grid.data_provider.bulkfeaturemanager:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.module.va_bulkfeaturemanager.grid.query_builder.bulkfeaturemanager'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'bulkFeatureManagerGrid'
  #4
  prestashop.module.va_bulkfeaturemanager.grid.factory.bulkfeaturemanager:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@prestashop.module.va_bulkfeaturemanager.grid.bulkfeaturemanager.grid_definition_factory'
      - '@prestashop.module.va_bulkfeaturemanager.grid.data_provider.bulkfeaturemanager'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

# service
  prestashop.module.va_bulkfeaturemanager.service.bulkfeaturemanager_service:
    class: 'Va_bulkfeaturemanager\Service\BulkFeatureManagerService'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'


## UnitfeatureConfiguration

## GridFeatureList
  prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.definition.factory.unit_feature_definition_factory:
    class: Va_bulkfeaturemanager\Grid\GridFeatureList\Definition\Factory\UnitFeatureDefinitionFactory
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.query.unit_feature_query_builder:
    class: 'Va_bulkfeaturemanager\Grid\GridFeatureList\Query\UnitFeatureQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'

  prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.definition.factory.unit_feature_definition_factory'
      - '@prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.data_provider'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'


  prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.data_provider:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@prestashop.module.va_bulkfeaturemanager.grid.grid_feature_list.query.unit_feature_query_builder'
      - '@prestashop.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'gridFeatureList'

  #form data provider

  Va_bulkfeaturemanager\Form\UnitFeatureConfiguration\UnitFeatureConfigurationFormType:
    class: Va_bulkfeaturemanager\Form\UnitFeatureConfiguration\UnitFeatureConfigurationFormType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
  #1
  prestashop.module.va_bulkfeaturemanager.form.unitfeatureconfiguration.data_provider:
    class: 'Va_bulkfeaturemanager\Form\UnitFeatureConfiguration\UnitFeatureConfigurationDataProvider'

  #2
  # data handler
  prestashop.module.va_bulkfeaturemanager.form.unitfeatureconfiguration.data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.va_bulkfeaturemanager.form.unitfeatureconfiguration.data_provider'
      - 'Va_bulkfeaturemanager\Form\UnitFeatureConfiguration\UnitFeatureConfigurationFormType'
      - 'BulkFeatureManager'
